### ISSUE TITLE
Feature Request: Expanded Rupee Counter

### ISSUE THREAD

**Issue by Cralex** [ShadowOne333/A-Link-to-the-Past-Redux#1]
Not sure if this is the right place to ask, but I’ve always wanted an optional patch that lets you hold more rupees in the base game, like you can in AST and (I think) some hacks. My reason for this is, when you get familiar with the game, you encounter rupees everywhere and max out easily. When this happens, they don’t feel like much of a reward anymore. This way at least, rupees can be used as a sort of “score” once you have more than you’re actually gonna use.

Just my two cents. Thanks for working on this incredible hack!

**Comment by ShadowOne333** [comment]
I think the "All-in-one" patch from Zeldix does offer a 4 digit rupee counter.
However, for the purposes of Redux, I don't think going that high would actually help at all.

The highest priced item in the whole game from what I remember are the Zora Flippers, and those are 500 rupees.
After that, the rest is pretty much up to personal preference. There's still the Bomb/Arrow upgrades, which can keep you busy for another thousand rupees, but that's about it.

Porting the 4 digit rupee counter from that code would certainly probe much more problematic than benefs, and besides, one of the main goals of this hack is to keep ALttP in tone with other Zeldas, and almost every other Zelda up to Majora's Mask also has 999 as their maximum, so keeping that amount in-line first with the other titles.

I'd have to give this one a pass right now, but it could be brought up in the future.
