### ISSUE TITLE
Using Linux needs some love

### ISSUE THREAD

**Issue by murmelbahn** [ShadowOne333/A-Link-to-the-Past-Redux#10]
Hi,
is it possible to give the linux building process some love?
The binaries you provide did not work for me.
I had to manualy compile asar and flips and then I came to
"Beginning main assembly code compilation with Asar..."
during the execution of make.sh

Sadly the script cancels with the following error:

`code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:403): error: (Efunction_not_found): Function 'stringlength("return")' wasn't found. [while 0 < stringlength("return")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:403): error: (Efunction_not_found): Function 'stringlength("of")' wasn't found. [while 0 < stringlength("of")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:403): error: (Efunction_not_found): Function 'stringlength("the")' wasn't found. [while 0 < stringlength("the")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:403): error: (Efunction_not_found): Function 'stringlength("king")' wasn't found. [while 0 < stringlength("king")]
code/text/retranslation/credits_ret.asm:42 (called from code/text/retranslation/credits_ret.asm:407): error: (Efunction_not_found): Function 'stringlength("HYRULE")' wasn't found. [while 0 < stringlength("HYRULE")]
code/text/retranslation/credits_ret.asm:42 (called from code/text/retranslation/credits_ret.asm:407): error: (Efunction_not_found): Function 'stringlength("CASTLE")' wasn't found. [while 0 < stringlength("CASTLE")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:411): error: (Efunction_not_found): Function 'stringlength("loyal")' wasn't found. [while 0 < stringlength("loyal")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:411): error: (Efunction_not_found): Function 'stringlength("priest")' wasn't found. [while 0 < stringlength("priest")]
code/text/retranslation/credits_ret.asm:42 (called from code/text/retranslation/credits_ret.asm:415): error: (Efunction_not_found): Function 'stringlength("CHAPEL")' wasn't found. [while 0 < stringlength("CHAPEL")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:421): error: (Efunction_not_found): Function 'stringlength("sahasralah")' wasn't found. [while 0 < stringlength("sahasralah")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:421): error: (Efunction_not_found): Function 'stringlength("s")' wasn't found. [while 0 < stringlength("s")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:421): error: (Efunction_not_found): Function 'stringlength("homecoming")' wasn't found. [while 0 < stringlength("homecoming")]
code/text/retranslation/credits_ret.asm:42 (called from code/text/retranslation/credits_ret.asm:425): error: (Efunction_not_found): Function 'stringlength("KAKARIKO")' wasn't found. [while 0 < stringlength("KAKARIKO")]
code/text/retranslation/credits_ret.asm:42 (called from code/text/retranslation/credits_ret.asm:425): error: (Efunction_not_found): Function 'stringlength("VILLAGE")' wasn't found. [while 0 < stringlength("VILLAGE")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:429): error: (Efunction_not_found): Function 'stringlength("vultures")' wasn't found. [while 0 < stringlength("vultures")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:429): error: (Efunction_not_found): Function 'stringlength("rule")' wasn't found. [while 0 < stringlength("rule")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:429): error: (Efunction_not_found): Function 'stringlength("the")' wasn't found. [while 0 < stringlength("the")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:429): error: (Efunction_not_found): Function 'stringlength("desert")' wasn't found. [while 0 < stringlength("desert")]
code/text/retranslation/credits_ret.asm:42 (called from code/text/retranslation/credits_ret.asm:433): error: (Efunction_not_found): Function 'stringlength("DESERT")' wasn't found. [while 0 < stringlength("DESERT")]
code/text/retranslation/credits_ret.asm:42 (called from code/text/retranslation/credits_ret.asm:433): error: (Efunction_not_found): Function 'stringlength("TEMPLE")' wasn't found. [while 0 < stringlength("TEMPLE")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:437): error: (Efunction_not_found): Function 'stringlength("bully")' wasn't found. [while 0 < stringlength("bully")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:437): error: (Elimit_reached): Over 20 errors detected. Aborting. [while 0 < stringlength("bully")]
A fatal error was detected while assembling the patch. Assembling aborted. Your ROM has not been modified.`

**Comment by ShadowOne333** [comment]
How did you try to run the binaries?

**Comment by ShadowOne333** [comment]
Did you `chmod +x flips` and `chmod +x asar` before compiling?
It could be an issue of the binaries not being executable when copied over at first.
If after trying that you still get the same issue, then it could be a problem with the binaries being eithe 32 or 64 bit only, not sure which one might be but I'm sure they should work on 32bit

**Comment by murmelbahn** [comment]
Oh good idea but i already give them the executive permissions. It seems like flip is working but when asar tries something it get some errors. Here is the full log:
`./make.sh -t -c                                                                                                                            ░▒▓ 1 х  root@Notebook-Tim  16:35:39
ROM detected. Verifying name...

Base ROM detected with proper name.
Verifying SHA-1 checksum hash...

Base ROM SHA-1 checksum verified.
Starting patching process...
Applying Map layout changes...
The patch was applied successfully!

Patching subtitle tilemapping...
The patch was applied successfully!

Beginning main assembly code compilation with Asar...

code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:403): error: (Efunction_not_found): Function 'stringlength("return")' wasn't found. [while 0 < stringlength("return")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:403): error: (Efunction_not_found): Function 'stringlength("of")' wasn't found. [while 0 < stringlength("of")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:403): error: (Efunction_not_found): Function 'stringlength("the")' wasn't found. [while 0 < stringlength("the")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:403): error: (Efunction_not_found): Function 'stringlength("king")' wasn't found. [while 0 < stringlength("king")]
code/text/retranslation/credits_ret.asm:42 (called from code/text/retranslation/credits_ret.asm:407): error: (Efunction_not_found): Function 'stringlength("HYRULE")' wasn't found. [while 0 < stringlength("HYRULE")]
code/text/retranslation/credits_ret.asm:42 (called from code/text/retranslation/credits_ret.asm:407): error: (Efunction_not_found): Function 'stringlength("CASTLE")' wasn't found. [while 0 < stringlength("CASTLE")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:411): error: (Efunction_not_found): Function 'stringlength("loyal")' wasn't found. [while 0 < stringlength("loyal")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:411): error: (Efunction_not_found): Function 'stringlength("priest")' wasn't found. [while 0 < stringlength("priest")]
code/text/retranslation/credits_ret.asm:42 (called from code/text/retranslation/credits_ret.asm:415): error: (Efunction_not_found): Function 'stringlength("CHAPEL")' wasn't found. [while 0 < stringlength("CHAPEL")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:421): error: (Efunction_not_found): Function 'stringlength("sahasralah")' wasn't found. [while 0 < stringlength("sahasralah")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:421): error: (Efunction_not_found): Function 'stringlength("s")' wasn't found. [while 0 < stringlength("s")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:421): error: (Efunction_not_found): Function 'stringlength("homecoming")' wasn't found. [while 0 < stringlength("homecoming")]
code/text/retranslation/credits_ret.asm:42 (called from code/text/retranslation/credits_ret.asm:425): error: (Efunction_not_found): Function 'stringlength("KAKARIKO")' wasn't found. [while 0 < stringlength("KAKARIKO")]
code/text/retranslation/credits_ret.asm:42 (called from code/text/retranslation/credits_ret.asm:425): error: (Efunction_not_found): Function 'stringlength("VILLAGE")' wasn't found. [while 0 < stringlength("VILLAGE")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:429): error: (Efunction_not_found): Function 'stringlength("vultures")' wasn't found. [while 0 < stringlength("vultures")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:429): error: (Efunction_not_found): Function 'stringlength("rule")' wasn't found. [while 0 < stringlength("rule")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:429): error: (Efunction_not_found): Function 'stringlength("the")' wasn't found. [while 0 < stringlength("the")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:429): error: (Efunction_not_found): Function 'stringlength("desert")' wasn't found. [while 0 < stringlength("desert")]
code/text/retranslation/credits_ret.asm:42 (called from code/text/retranslation/credits_ret.asm:433): error: (Efunction_not_found): Function 'stringlength("DESERT")' wasn't found. [while 0 < stringlength("DESERT")]
code/text/retranslation/credits_ret.asm:42 (called from code/text/retranslation/credits_ret.asm:433): error: (Efunction_not_found): Function 'stringlength("TEMPLE")' wasn't found. [while 0 < stringlength("TEMPLE")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:437): error: (Efunction_not_found): Function 'stringlength("bully")' wasn't found. [while 0 < stringlength("bully")]
code/text/retranslation/credits_ret.asm:23 (called from code/text/retranslation/credits_ret.asm:437): error: (Elimit_reached): Over 20 errors detected. Aborting. [while 0 < stringlength("bully")]
A fatal error was detected while assembling the patch. Assembling aborted. Your ROM has not been modified.`

My Debian is a x64 installation, so hopefully this should not be an issue.

**Comment by ShadowOne333** [comment]
That's weird, I can compile with the same -t -c arguments, and it finished without errors for me.
Have you compiled a recent version of Asar by any chance and are using that?

**Comment by murmelbahn** [comment]
Yes! I have used the latest version of Asar. Strange, why is it working for you? Did you use the binaries from this repo?

**Comment by ShadowOne333** [comment]
Yes, I'm using the binaries from the repo.
Let me try compiling the latest Asar version and test with that.

**Comment by murmelbahn** [comment]
Hi,
thanks for your quick answer. With `asar_2_beta` I was able to let the script run without the errors.
After asar your script uses `scompress`. As with the other binaries I'm not able to run it. So I tried to compile
it but was not able to get a working binary of it. Can you give me a hint about compiling `scompress` ? Did you use
special paramters?

**Comment by ShadowOne333** [comment]
Enter the directory `/bin/scompress/scompress-master/scompress/`, open terminal in this directory and then do the following:
`cmake . && make`

Afterwards, you should a freshly generated `scompress` binary in the same folder, that should be the correct one to use.

**Comment by murmelbahn** [comment]
okay when I'm building from your scompress files I get the same error when executing the binary as when I'm building from the authors repo: `Can't open testsnestilebpp3.tl : No such file or directory`

Did you have IRC, Discord or something else so we can figure out why things are not workinga as intended? Yesterday I tried another Debian installation with the same results. I saw you already updated the ReadMe.md but I think we have also to figure out how to get scompress running.

**Comment by ShadowOne333** [comment]
You can find me on Discord as ShadowOne333#4981 
We can continue the discussion there if you like, though I don't recall getting that issue for scompress precisely, I'll try recompiling again and testing it just to be sure.

**Comment by ShadowOne333** [comment]
Did you try to contact me on Discord a couple days ago?
If you did, please do so again, i might have dismissed it thinking it was spam.

**Comment by eyevandy** [comment]
I have a couple more suggestions for the readme.

If you can't run the binaries because of a 32/64 bit mismatch, bash will give a 'file not found' error for the binaries. I had never run into this before and this is obviously a very confusing way to report this error so I tried it in like 4 different Linux boxes before I ran the particular Google search you'd need to discover this information. You already tip us off that the binaries might not work but it would probably be helpful to specifically call out those FNF errors and save the next guy some frustration.

The other issue I ran into is that asar doesn't correctly declare the version of cmake it needs to build in the v2 beta branch. This is very much not obvious when you run it with an outdated cmake (which I got through apt-get on Debian). It tries to run but chokes on a bunch of commands in the cmake build file. You need cmake v3.15 or newer in order to compile asar v2 beta. Fortunately it's easy to just download a different binary from the release list on github and run it from that.

Thanks Shadow! I really appreciate how modular this system is so that I can get the exact version of LTTP that I want.

**Comment by ShadowOne333** [comment]
@eyevandy thanks for the suggestions, I have added that information for the errors and cmake into the ReadMe now, so it should now be accounted for.
I'll go ahead and close this issue since it seems to be properly handled now with the instructions provided in the ReadMe.
