### ISSUE TITLE
Issue with using MSU-1 tracks

### ISSUE THREAD

**Issue by darkpaladin109** [ShadowOne333/A-Link-to-the-Past-Redux#11]
I've been trying to use some this romhack alongside some MSU-1 files, but I just can't seem to get it to work.
After applying the patch and dropping it into the folder with my music files, it doesn't run properly. All I get is a black screen while the warp noise from the game plays.
I'm not sure what I'm doing wrong here, but it runs fine if I either change the name or move the rom somewhere else.

**Comment by darkpaladin109** [comment]
I didn't use that particular patch, nor did I have the FMV file.

**Comment by ShadowOne333** [comment]
Oh I see, then it might be that.
Please check that the whole MSU stuff without track 35 works properly before patching in the "Enable FMV" IPS.
Once you confirm that Redux works fine with the MSU-1 tracks, then you can go ahead and patch the "Enable FMV" IPS and also add track 35 into your PCM files.

Please let me know if that worked so I can close down the issue.

**Comment by darkpaladin109** [comment]
Base patch isn't working with my MSU-1 files. Here's what my MSU-1 folder looks like, in case there's anything wrong there.
It seems to work just fine using only the MSU-1 patch, but not when I apply either of the two primary Redux patches.
It loads properly when I apply the patches **without** putting it into the MSU-1 folder, so I think it must relate to something in there.
Sorry for all the trouble about this.
![zelda3 redux msu1](https://user-images.githubusercontent.com/17275997/227011413-e4a9f270-3b25-4ad3-8b4c-46200b1571b1.png)

**Comment by ShadowOne333** [comment]
Wait, are you applying the MSU-1 patch and then Redux?
Redux/Retranslation alone already has MSU-1 patched in, you don't need to apply anything else.
Make sure you only patch either Redux or Retranslation, and test your MSU-1 files again with just that.

**Comment by ShadowOne333** [comment]
Does Redux boot on its own without any of the MSU-1 files?
I feel like the issue here might be a headered ROM or something of the like.

**Comment by darkpaladin109** [comment]
Boots up without any MSU-1 files. Neither NSRT or SNES Rom Utility show a header.

**Comment by ShadowOne333** [comment]
Can you show me a picture of the files and how they are organized on your end?
Also, what emulator are you trying to run this on?

**Comment by darkpaladin109** [comment]
This is how my MSU-1 folder normally looks on my end. Emulator I am trying to run it on is SNES9x version 1.60
![zelda3 redux msu1](https://user-images.githubusercontent.com/17275997/227043679-1c4cbaea-3ca1-4669-bc65-64d1a3d03c2b.png)

**Comment by ShadowOne333** [comment]
Delete the "alttp_msu1.ips" file (the one with the Heart icon), that one is getting applied on top of Redux, and it's most likely what is causing the crashes.

**Comment by darkpaladin109** [comment]
That seems to have fixed the issues. Thanks so much for the help!

**Comment by ShadowOne333** [comment]
You're welcome! 

Be careful when putting IPS patches that share the same name as the ROM, as many emulators have autopatching features where a patch with the same name gets applied automatically.

Enjoy the hack!
