### ISSUE TITLE
"Triforce of the Gods Subtitle" optional patch results in a corrupted ROM

### ISSUE THREAD

**Issue by TheGershon** [ShadowOne333/A-Link-to-the-Past-Redux#13]
Applied with Floating IPS, patching Triforce of the Gods Subtitle onto either Redux or Retranslation Redux 10.2 results in a corrupted rom:
![The Legend of Zelda_ Triforce of the Gods  Redux10 2 JPSubtitle -001](https://user-images.githubusercontent.com/6880780/226766908-1ce3d6f9-8199-4958-be1f-7a2a842addd4.png)
![The Legend of Zelda_ Triforce of the Gods  Redux10 2 JPSubtitle -002](https://user-images.githubusercontent.com/6880780/226766914-75f0f3d6-589a-4955-a9c7-ff07e95620d9.png)

**Comment by TheGershon** [comment]
I downloaded from romhacking.net, and applied the subtitle patch after patching either flavor of redux onto a no-intro verified rom.
MD5 of Redux + patch: eddbd7a05e4d7f26768f96216e3a8028
MD5 of Retranslation + patch: 764337530dc2ad0e318c7aaa97210190

**Comment by ShadowOne333** [comment]
Can you try with the ones found in this link?
https://github.com/ShadowOne333/A-Link-to-the-Past-Redux/tree/main/patches/Optional

Let me know what your results are

**Comment by TheGershon** [comment]
Same results, the files end up with the exact same checksums even.

**Comment by ShadowOne333** [comment]
Can you tell me if the following patch fixes the issue on your end for both Redux and Retranslation?

[Triforce of the Gods Subtitle.zip](https://github.com/ShadowOne333/A-Link-to-the-Past-Redux/files/11041649/Triforce.of.the.Gods.Subtitle.zip)

**Comment by TheGershon** [comment]
Seems to have done the trick:
![The Legend of Zelda_ Triforce of the Gods  RetranslationRedux10 2 JPSubtitle -001](https://user-images.githubusercontent.com/6880780/227059888-e36e55eb-735c-4b79-adf3-567a97e229f2.png)

**Comment by ShadowOne333** [comment]
Awesome! Does it work for both Redux and Retranslation?

**Comment by TheGershon** [comment]
Yup, and I just made sure it works when combined with other patches too.

**Comment by ShadowOne333** [comment]
Lovely, I'll close up the issue then.

Enjoy the hack!
