### ISSUE TITLE
v10.2 crash on mednafen

### ISSUE THREAD

**Issue by banditkroot** [ShadowOne333/A-Link-to-the-Past-Redux#14]
The v10.2 main patch crash with mednafen 1.31 Linux, but it works with the nightly bsnes.
The game crash on the triforce animation logo when the first music should start, screen goes black and no sound anymore.
The v10.1 still working.

**Comment by ShadowOne333** [comment]
Isn't Mednafen quite obsolete? It's been years since I tried it, but I have never tried Redux on it.
v10.2 should work on latest Snes9x, bsnes and Mesen-S, those are the 3 main Snes emus to try with it.

**Comment by banditkroot** [comment]
Mednafen is always maintained.
Snes9x need to compile.
Mesen-S use .NET...
bsnes high cpu usage and lag on Linux... And no multi screen support.
ares it works, but no multi screen support.

**Comment by ShadowOne333** [comment]
What patches did you use and in what order did you apply them?

**Comment by banditkroot** [comment]
I tried the two main patch sperately, nothing else.
I upload a video https://youtu.be/RIoLERl8iPE I heard a sound before it crash.

**Comment by ShadowOne333** [comment]
Try on Snes9x. I have never tried Mednafen nor know how updated it is in terms of compatibility in general.
The only change between v10.1 and v10.2 was only one pointer changed for FastROM and that's it.

**Comment by banditkroot** [comment]
It works on snes9x.
I tried again on mednafen , it works without the msu-1 music.
Thank you for your time.

**Comment by ShadowOne333** [comment]
I think it might be that the IPS file has the same name as the ROM, and therefore gets automatically patched over the Redux ROM (since that's a feature some emulators have). Deleting the IPS should do it.

Glad you got it working tho! I'll go ahead an close the issue
