### ISSUE TITLE
Text errors on death mountain characters

### ISSUE THREAD

**Issue by rgarretson84** [ShadowOne333/A-Link-to-the-Past-Redux#17]
Two characters on death mountain in the dark world (Zelda Wiki calls them "Bully" and "Bully's Friend", the monster looking kid that bounces around the pink ball and they don't attack Link) have their text cut-off in the standard Redux hack and the retranslation version. 

Additionally, in the retranslation patch bumping into Bully and triggering his conversation corrupts the screen and freezes the game.

Tested on v10.2.2 using latest bsnes core in retroarch - save state near characters attached:
[The Legend of Zelda - A Link to the Past [Redux Hack].zip](https://github.com/ShadowOne333/A-Link-to-the-Past-Redux/files/11301723/The.Legend.of.Zelda.-.A.Link.to.the.Past.Redux.Hack.zip)

**Comment by ShadowOne333** [comment]
Thank you for the report.
I don't have access to a PC atm, but in the meantime, could you share picture of the exact momento the issue occurs for both versions?

Pictures from right before the text gets cutoff and another when the cut-off occurs. The images will greatly help to pinpoint the exact problem in the script so when I get to the PC I can fix them asap.

**Comment by rgarretson84** [comment]
Thanks ShadowOne333, I just did more testing around this and apparently my issues were caused by a save state that was corrupted somehow, could be because I tried using a state across multiple versions of the redux hack (just weird because didn't run into any simlar issues with any other part of the game or other character conversations, other than what you already fixed from the pendant of wisdom message).

I've confirmed that the conversation text issues I mentioned before do not occur in either standard redux or retranslation redux when starting from a save instead of the emulator state.

Love the hack! Apologies for the error on my part, please consider this issue closed.

**Comment by ShadowOne333** [comment]
Ah it's fine! Thank you for confirming it was a save state issue. What happened most likely is that the script stuff got moved around when I did the Pendant text fix, and the game loading the save state was now trying to read text that was garbage.

Hope you enjoy the hack!
