### ISSUE TITLE
Any way to save the compiled IPS patch instead of only the patched ROM?

### ISSUE THREAD

**Issue by fooness** [ShadowOne333/A-Link-to-the-Past-Redux#18]
I’d like to compile a set of patches and keep them.

Is there any way to save the patches after building instead of only the patched ROM?

---

EDIT: It seems `flips` can be used to `--create` these patches.

… though it would be great if this could happen (optionally?) within the regular build process.

**Comment by ShadowOne333** [comment]
It's possible yeah, but from what I know the script I made should output an IPS already inside the "patches" folder alongside the output ROM saved in "out"

**Comment by fooness** [comment]
I’m not sure it does. *Or maybe I’m missing some flag or option.*

```
$ ./make.sh -o -r

[…]

Creating **Zelda3-Redux.ips** patch...
The patch was created successfully!
Redux compilation finished at 07:08:59 Fri 08/Sep/2023!
```

No luck using e.g. `find` to search for that `Zelda3-Redux.ips`; it only finds `out/Zelda3-Redux.sfc` …

**Comment by ShadowOne333** [comment]
It's not called `Zelda3-Redux.ips`, but rather `Link to the Past Redux.ips`
You can verify this by deleting that IPS and running the make script again, it will create it after it finishes.
