### ISSUE TITLE
How to make pcm files work without msu file

### ISSUE THREAD

**Issue by chrcoluk** [ShadowOne333/A-Link-to-the-Past-Redux#23]
I have the custom music tracks but there is no msu file, just pcm files.

Is there a way to create a msu file for them or to use them without a msu file?

Or is this outside of the scope of the mod?

**Comment by ShadowOne333** [comment]
The mod only provides MSU-1 implementation, but how MSU is handled is entirely dependant on either the emulators or the creators of MSU itself.

From what I know, the msu file itself is just a blank/empty file that should have the same name as the ROM and end in .msu, like this:
"The Legend of Zelda - A Link to the Past.msu"

**Comment by chrcoluk** [comment]
I found other music sets now which all have a msu file and work in game, so I will close this, thanks.
