### ISSUE TITLE
pressing select asks me if I want to do the digging game???

### ISSUE THREAD

**Issue by pleasejustgo** [ShadowOne333/A-Link-to-the-Past-Redux#3]
Hi, so I wanted to report this issue. I applied these in this order:
-redux
-retranslation
-triforce of the gods subtitle
-disable dash turning
-enable fmv
-kakariko shortcut
-move blocks
-original bomb-arrow #

I only noticed when I was in the castle dungeon at the beginning that when I press select, the game asks me if I want to do the digging game for 80 rupees. I was like what?? If you choose no, it brings you back to the title screen. If yes. then you just continue playing without losing money. You don't have 80 rupees at that point anyways.

**Comment by ShadowOne333** [comment]
You only need to apply either Redux or Retranslation, not both.
So if you want Retranslation, only patch the Retranslation IPS, and then your optional patches.
