### ISSUE TITLE
Mednafen/Beetle Supafaust core requires .sfc extension for MSU-1 support (readme is not accurate about file extenson)

### ISSUE THREAD

**Issue by nl255** [ShadowOne333/A-Link-to-the-Past-Redux#5]
In the readme it says it doesn't matter if you use smc or sfc but apparently the Mednafen/Bettle "supafaust" core only supports msu1 if the rom extension is .sfc for some reason.  So I would recommend updating the readme file to mention that sfc is recommended as some emulators don't like other extensions when it comes to msu hacks.

**Comment by ShadowOne333** [comment]
Thanks for the heads up.
I have updated the ReadMe accordingly to specify that only SFC extensions should be used for compatibility with other emulators.
